// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StripPayment.Server.Data;

#nullable disable

namespace StripPayment.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("StripPayment.Shared.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "25146bd4-7ffb-4b0b-a232-42c12a78562f",
                            Description = "Description of product 0, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/0/500",
                            Price = 1000m,
                            Title = "Product 0"
                        },
                        new
                        {
                            Id = "733157a0-9a0e-44a2-86b9-126f6a0ba951",
                            Description = "Description of product 1, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/1/500",
                            Price = 1001m,
                            Title = "Product 1"
                        },
                        new
                        {
                            Id = "ae4888c6-4dad-424f-8330-82c9abdfdc95",
                            Description = "Description of product 2, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/2/500",
                            Price = 1002m,
                            Title = "Product 2"
                        },
                        new
                        {
                            Id = "5ab96d0a-eda4-46ca-981e-8747ce7fabdd",
                            Description = "Description of product 3, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/3/500",
                            Price = 1003m,
                            Title = "Product 3"
                        },
                        new
                        {
                            Id = "b57a4be2-7190-407c-bc8a-ade622695e9b",
                            Description = "Description of product 4, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/4/500",
                            Price = 1004m,
                            Title = "Product 4"
                        },
                        new
                        {
                            Id = "ff02cebd-a8d9-4097-844a-f61b8652bcca",
                            Description = "Description of product 5, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/5/500",
                            Price = 1005m,
                            Title = "Product 5"
                        },
                        new
                        {
                            Id = "625bfbc4-c392-46d2-bb23-5a779d364ca0",
                            Description = "Description of product 6, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/6/500",
                            Price = 1006m,
                            Title = "Product 6"
                        },
                        new
                        {
                            Id = "ec075572-8e3b-4352-9168-44f5f43bd8df",
                            Description = "Description of product 7, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/7/500",
                            Price = 1007m,
                            Title = "Product 7"
                        },
                        new
                        {
                            Id = "bc3b2681-985e-4539-804f-21eee1db0b90",
                            Description = "Description of product 8, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/8/500",
                            Price = 1008m,
                            Title = "Product 8"
                        },
                        new
                        {
                            Id = "a7ba0fac-df5a-434a-9bdc-fca0fa25d1d1",
                            Description = "Description of product 9, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/9/500",
                            Price = 1009m,
                            Title = "Product 9"
                        },
                        new
                        {
                            Id = "929fb89d-3d74-421a-bc4e-6e0ff6509f2b",
                            Description = "Description of product 10, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/10/500",
                            Price = 1010m,
                            Title = "Product 10"
                        },
                        new
                        {
                            Id = "e8f720b4-537b-4019-b733-4907fed72368",
                            Description = "Description of product 11, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/11/500",
                            Price = 1011m,
                            Title = "Product 11"
                        },
                        new
                        {
                            Id = "db0cf9d9-7571-4aee-8dfc-faeba947997f",
                            Description = "Description of product 12, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/12/500",
                            Price = 1012m,
                            Title = "Product 12"
                        },
                        new
                        {
                            Id = "e9e346fa-d83b-4dde-bb0c-37681585c43e",
                            Description = "Description of product 13, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/13/500",
                            Price = 1013m,
                            Title = "Product 13"
                        },
                        new
                        {
                            Id = "3e3f7647-5afc-4d8e-9fdc-642c255ab369",
                            Description = "Description of product 14, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/14/500",
                            Price = 1014m,
                            Title = "Product 14"
                        },
                        new
                        {
                            Id = "11dee476-6420-4f55-aed8-5783c6ccff89",
                            Description = "Description of product 15, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/15/500",
                            Price = 1015m,
                            Title = "Product 15"
                        },
                        new
                        {
                            Id = "ab20b53f-0f69-4a5d-a560-7d05bd4e8dda",
                            Description = "Description of product 16, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/16/500",
                            Price = 1016m,
                            Title = "Product 16"
                        },
                        new
                        {
                            Id = "638aeca8-cad2-4bc5-8a6e-dad58035b34d",
                            Description = "Description of product 17, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/17/500",
                            Price = 1017m,
                            Title = "Product 17"
                        },
                        new
                        {
                            Id = "8611fa38-85c7-4d32-bd63-e23168930b94",
                            Description = "Description of product 18, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/18/500",
                            Price = 1018m,
                            Title = "Product 18"
                        },
                        new
                        {
                            Id = "43fa810a-f848-4a3a-9685-ca253e7c45c3",
                            Description = "Description of product 19, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/19/500",
                            Price = 1019m,
                            Title = "Product 19"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
